-- liquibase formatted sql

-- changeset emil:1
create table notification_task
(
    id                     bigint generated by default as identity
        primary key,
    chat_id                bigint NOT NULL,
    notification_date_time timestamp NOT NULL,
    notification_message   varchar(255) NOT NULL ,
    status                 varchar(255) NOT NULL DEFAULT 'SCHEDULED'
);

alter table notification_task
    owner to "adminBot";

-- changeset emil:2
CREATE INDEX notification_task_idx ON notification_task(notification_date_time) WHERE status = 'SCHEDULE';

-- changeset emil:3
ALTER TABLE notification_task ADD COLUMN sent_date timestamp;
